/* Generated by Yosys 0.69 (git sha1 9f75ca1f9, Release, GNU /usr/bin/c++ 13.3.0) */

module mult_array(clk, rst_n, a, b, p);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  output [7:0] p;
  wire [7:0] p;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire [3:0] a_reg;
  wire [3:0] b_reg;
  wire [4:0] c3;
  wire \fa1_0.sum ;
  wire \fa2_0.sum ;
  wire \fa3_0.sum ;
  wire \fa3_1.sum ;
  wire \fa3_2.sum ;
  wire \fa3_3.sum ;
  wire [3:0] pp0;
  sky130_fd_sc_hd__and2_0 _043_ (
    .A(a_reg[0]),
    .B(b_reg[0]),
    .X(pp0[0])
  );
  sky130_fd_sc_hd__nand2_1 _044_ (
    .A(b_reg[3]),
    .B(a_reg[0]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _045_ (
    .A(_000_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _046_ (
    .A(b_reg[0]),
    .B(a_reg[3]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _047_ (
    .A(b_reg[0]),
    .B(a_reg[2]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _048_ (
    .A(a_reg[1]),
    .B(b_reg[1]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _049_ (
    .A(b_reg[1]),
    .B(a_reg[2]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand4_1 _050_ (
    .A(b_reg[0]),
    .B(a_reg[1]),
    .C(b_reg[1]),
    .D(a_reg[2]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand4_1 _051_ (
    .A(a_reg[0]),
    .B(b_reg[0]),
    .C(a_reg[1]),
    .D(b_reg[1]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a21boi_0 _052_ (
    .A1(_005_),
    .A2(_007_),
    .B1_N(_006_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _053_ (
    .A(_002_),
    .B(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__and2_0 _054_ (
    .A(a_reg[0]),
    .B(b_reg[2]),
    .X(_010_)
  );
  sky130_fd_sc_hd__o21ai_0 _055_ (
    .A1(pp0[0]),
    .A2(_004_),
    .B1(_003_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__or3_1 _056_ (
    .A(pp0[0]),
    .B(_003_),
    .C(_004_),
    .X(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _057_ (
    .A(_011_),
    .B(_012_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__a32oi_1 _058_ (
    .A1(_010_),
    .A2(_011_),
    .A3(_012_),
    .B1(b_reg[2]),
    .B2(a_reg[1]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__and4_1 _059_ (
    .A(a_reg[1]),
    .B(_010_),
    .C(_011_),
    .D(_012_),
    .X(_015_)
  );
  sky130_fd_sc_hd__nor3_1 _060_ (
    .A(_009_),
    .B(_014_),
    .C(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__o21a_1 _061_ (
    .A1(_014_),
    .A2(_015_),
    .B1(_009_),
    .X(_017_)
  );
  sky130_fd_sc_hd__o21a_1 _062_ (
    .A1(_016_),
    .A2(_017_),
    .B1(_001_),
    .X(_018_)
  );
  sky130_fd_sc_hd__o21ai_0 _063_ (
    .A1(_016_),
    .A2(_017_),
    .B1(_001_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _064_ (
    .A(b_reg[3]),
    .B(a_reg[1]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _065_ (
    .A(a_reg[2]),
    .B(b_reg[2]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _066_ (
    .A(a_reg[3]),
    .B(b_reg[1]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a21oi_1 _067_ (
    .A1(_005_),
    .A2(_007_),
    .B1(_002_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__a21oi_1 _068_ (
    .A1(_006_),
    .A2(_022_),
    .B1(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _069_ (
    .A(_024_),
    .SLEEP(_021_),
    .X(_025_)
  );
  sky130_fd_sc_hd__nand2b_1 _070_ (
    .A_N(_024_),
    .B(_021_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__xnor2_1 _071_ (
    .A(_021_),
    .B(_024_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o21ba_1 _072_ (
    .A1(_009_),
    .A2(_015_),
    .B1_N(_014_),
    .X(_028_)
  );
  sky130_fd_sc_hd__xnor2_1 _073_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xnor2_1 _074_ (
    .A(_020_),
    .B(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _075_ (
    .A(_018_),
    .B(_030_),
    .Y(\fa3_1.sum )
  );
  sky130_fd_sc_hd__nand2_1 _076_ (
    .A(b_reg[3]),
    .B(a_reg[3]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _077_ (
    .A(a_reg[3]),
    .B(b_reg[2]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a21oi_1 _078_ (
    .A1(_026_),
    .A2(_028_),
    .B1(_025_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2b_1 _079_ (
    .A_N(_023_),
    .B(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand3_1 _080_ (
    .A(a_reg[3]),
    .B(b_reg[2]),
    .C(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _081_ (
    .A(b_reg[3]),
    .B(a_reg[2]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__maj3_1 _082_ (
    .A(_019_),
    .B(_020_),
    .C(_029_),
    .X(_037_)
  );
  sky130_fd_sc_hd__xnor3_1 _083_ (
    .A(_023_),
    .B(_032_),
    .C(_033_),
    .X(_038_)
  );
  sky130_fd_sc_hd__maj3_1 _084_ (
    .A(_036_),
    .B(_037_),
    .C(_038_),
    .X(_039_)
  );
  sky130_fd_sc_hd__a21oi_1 _085_ (
    .A1(_035_),
    .A2(_039_),
    .B1(_031_),
    .Y(c3[4])
  );
  sky130_fd_sc_hd__xor2_1 _086_ (
    .A(_036_),
    .B(_037_),
    .X(_040_)
  );
  sky130_fd_sc_hd__xnor2_1 _087_ (
    .A(_038_),
    .B(_040_),
    .Y(\fa3_2.sum )
  );
  sky130_fd_sc_hd__xnor3_1 _088_ (
    .A(_031_),
    .B(_035_),
    .C(_039_),
    .X(\fa3_3.sum )
  );
  sky130_fd_sc_hd__nor3_1 _089_ (
    .A(_001_),
    .B(_016_),
    .C(_017_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nor2_1 _090_ (
    .A(_018_),
    .B(_041_),
    .Y(\fa3_0.sum )
  );
  sky130_fd_sc_hd__xnor2_1 _091_ (
    .A(_010_),
    .B(_013_),
    .Y(\fa2_0.sum )
  );
  sky130_fd_sc_hd__a22oi_1 _092_ (
    .A1(b_reg[0]),
    .A2(a_reg[1]),
    .B1(b_reg[1]),
    .B2(a_reg[0]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _093_ (
    .A(_007_),
    .SLEEP(_042_),
    .X(\fa1_0.sum )
  );
  sky130_fd_sc_hd__dfrtp_1 _094_ (
    .CLK(clk),
    .D(pp0[0]),
    .Q(p[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _095_ (
    .CLK(clk),
    .D(\fa1_0.sum ),
    .Q(p[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _096_ (
    .CLK(clk),
    .D(\fa2_0.sum ),
    .Q(p[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _097_ (
    .CLK(clk),
    .D(\fa3_0.sum ),
    .Q(p[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _098_ (
    .CLK(clk),
    .D(\fa3_1.sum ),
    .Q(p[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _099_ (
    .CLK(clk),
    .D(\fa3_2.sum ),
    .Q(p[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _100_ (
    .CLK(clk),
    .D(\fa3_3.sum ),
    .Q(p[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _101_ (
    .CLK(clk),
    .D(c3[4]),
    .Q(p[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _102_ (
    .CLK(clk),
    .D(a[0]),
    .Q(a_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _103_ (
    .CLK(clk),
    .D(a[1]),
    .Q(a_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _104_ (
    .CLK(clk),
    .D(a[2]),
    .Q(a_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _105_ (
    .CLK(clk),
    .D(a[3]),
    .Q(a_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _106_ (
    .CLK(clk),
    .D(b[0]),
    .Q(b_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _107_ (
    .CLK(clk),
    .D(b[1]),
    .Q(b_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _108_ (
    .CLK(clk),
    .D(b[2]),
    .Q(b_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _109_ (
    .CLK(clk),
    .D(b[3]),
    .Q(b_reg[3]),
    .RESET_B(rst_n)
  );
  assign c3[0] = 1'h0;
endmodule
